# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "3a:5b:38:f3:e9:d0:47:89:d0:09:86:63:e0:fc:74:24"

      - run: |
        echo "${SSH_HOST} ecdsa-sha2-nistp256\n${REMOTE_HOSTKEY}" >> ~/.ssh/known_hosts

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      # - run: gradle test

      # build
      - run: gradle bootJar

      - deploy:
          name: deploy
          command: |
            scp build/libs/* ${SSH_USER}@${SSH_HOST}:~/codepass/build/
            ssh ${SSH_USER}@${SSH_HOST} ~/codepass/reload.sh
