spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codepass?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: test
    password: test
  data:
    mongodb: null
