# Spring Boot 配置

server:
  port: ${APP_PORT:8080}

jwt:
  expire: 432000000
  secret: iamthesecretkey

spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:mysql://katty.top:3306/codepass?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: codepass
    password: codepass
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
  data:
    mongodb:
      host: katty.top
      port: 27017
      database: codepass
      username: codepass
      password: codepass
  security:
    user:
      name: admin
      password: admin
      roles: [ 'admin' ]