# Spring Boot 配置

server:
  port: ${APP_PORT:8000}

spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:mysql://katty.top:3306/codepass?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: codepass
    password: codepass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: katty.top
      port: 27017
      database: codepass
      username: codepass
      password: codepass

springdoc:
  api-docs:
    enabled: true
    path: /oa/v3/api-docs
  swagger-ui:
    enabled: true
    path: /oa/swagger-ui.html
